{{- $secretName := printf "%s-relay-shared-secret" (include "kebabcase-release-name" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $relaySecret := "" -}}
{{- if $existingSecret -}}
  {{- $relaySecret = index $existingSecret.data "RELAY_SECRET" | b64dec -}}
{{- else -}}
  {{- $relaySecret = randAlphaNum 32 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kebabcase-release-name" . }}-relay-shared-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "recommended-labels" . | indent 4 }}
data:
  BSEE_REQUEST_RELAY_SECRET: {{ $relaySecret | b64enc }}
  RELAY_SECRET: {{ $relaySecret | b64enc }}
