{{- $secretName := printf "%s-scanning-shared-secret" (include "kebabcase-release-name" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $apiKey := "" -}}
{{- if $existingSecret -}}
  {{- $apiKey = index $existingSecret.data "BSEE_HOSTED_SCANNING_MACHINE_API_KEY" | b64dec -}}
{{- else -}}
  {{- $apiKey = randAlphaNum 32 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kebabcase-release-name" . }}-scanning-shared-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "recommended-labels" . | indent 4 }}
data:
  BSEE_HOSTED_SCANNING_MACHINE_API_KEY: {{ $apiKey | b64enc }}
