{{- if not .Values.services.webServer.existingSecret -}}
{{- $secretName := printf "%s-web-server-secret" (include "kebabcase-release-name" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $password := "" -}}
{{- if $existingSecret -}}
  {{- $password = index $existingSecret.data "BSEE_CLIENT_KEYSTORE_PASSWORD" | b64dec -}}
{{- else -}}
  {{- $password = randAlphaNum 20 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kebabcase-release-name" . }}-web-server-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: web-server
    app.kubernetes.io/component: server
{{ include "recommended-labels" . | indent 4 }}
data:
  BSEE_CLIENT_KEYSTORE_PASSWORD: {{ $password | b64enc }}
  BSEE_CLIENT_TRUSTSTORE_PASSWORD: {{ $password | b64enc }}
{{- end }}