kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "kebabcase-release-name" . }}-scan-controller-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: scan-controller
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "kebabcase-release-name" . }}-scanner-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: scanner
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}
automountServiceAccountToken: false
