apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kebabcase-release-name" . }}-connection-relay
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: connection-relay
    app.kubernetes.io/component: relay
{{ include "recommended-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: connection-relay
      app.kubernetes.io/component: relay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: connection-relay
        app.kubernetes.io/component: relay
{{ include "recommended-labels" . | indent 8 }}
    spec:
{{ include "image-pull-secrets" . | indent 6 }}
      serviceAccountName: {{ include "kebabcase-release-name" . }}-connection-relay-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 42877
        runAsGroup: 42877
        fsGroup: 42877
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: connection-relay
          image: {{ include "relay-image" . }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: RELAY_PORT
              value: "8080"
            - name: BSEE_LOGS_DIRECTORY
              value: "/home/burpsuite/logs"
            - name: RELAY_TLS_SKIP_VERIFICATION
              value: {{ .Values.services.webServer.skipTlsVerification | quote }}
          envFrom:
            - secretRef:
                name: {{ include "kebabcase-release-name" . }}-relay-shared-secret
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: {{ include "kebabcase-release-name" . }}-volume
              mountPath: /home/burpsuite
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 42877
            capabilities:
              drop:
                - ALL
      volumes:
        - name: {{ include "kebabcase-release-name" . }}-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim }}
