apiVersion: v1
kind: Service
metadata:
  name: {{ include "kebabcase-release-name" . }}-connection-relay
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: connection-relay
    app.kubernetes.io/component: relay
{{ include "recommended-labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: connection-relay
    app.kubernetes.io/component: relay
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http