apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-reader-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterprise-server
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kebabcase-release-name" . }}-enterprise-server-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-reader-role