kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterprise-server
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "delete", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs/status"]
    verbs: ["get"]