apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kebabcase-release-name" . }}-enterprise-server-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: enterprise-server
    app.kubernetes.io/component: rbac
{{ include "recommended-labels" . | indent 4 }}